apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootf-final-product-deploy
  labels:
    app: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: products-app
        image: nanita462/fb-backend-products:1.0.0
        ports:
        - containerPort: 3001
